### ISSUE TITLE
[Bug]: OBD-2000 Not enough memory -> 'No Enough Memory'

### ISSUE THREAD

**Issue by bigradish** [oceanbase/obdeploy#178]
例如，你的错误提示：
`[ERROR] OBD-2000: (127.0.0.1) not enough memory.`
难道不应该是"no enough memory"吗？
建议你们找几个英语水平高的人，仔细检查修改一下你们的英文表达，以免让人觉得你们软件质量也low。
谢谢！

**Comment by frf12** [comment]
Thank you for your feedback. In informational messages, such as signs or alerts, it is common to use "No" to indicate prohibition or negation. For example, phrases like "No parking" or "No smoking" are commonly used to communicate that parking or smoking is not allowed.

However, when expressing an insufficient or inadequate quantity, it is more appropriate to use the phrase "Not enough" followed by the noun. For instance, when checking memory availability, it is more natural to say "Not enough memory" rather than "No enough memory".

The reason for using "Not enough memory" is that "not enough" is a commonly used English phrase to convey insufficiency. It has become an established and widely recognized expression in the English language. By using "not enough", we ensure clarity and adhere to English language conventions.

Thank you again for your feedback. We appreciate your input and will conduct a thorough review of similar issues to ensure consistency and clarity in our messaging.

**Comment by bigradish** [comment]
@frf12 ,

Thank you for your detailed answers. Sorry, I don't think so. I still think "no enough memory" is better in this context, and "insufficient memory" is somehow better than "not enough memory".

**Comment by caifeizhi** [comment]
> Thank you for the feedback, this is indeed a typo.

Maybe I misunderstood. I consulted several experts (including ChatGPT), and also conducted a search for relevant records. I found  that 'Not Enough Memory' maybe the correct grammar;
refs:
- https://www.quora.com/Of-these-two-sentences-which-one-is-correct-There-is-no-enough-time-and-There-is-not-enough-time-Why
- https://ell.stackexchange.com/questions/226700/which-one-is-better-not-enough-or-no-enough
