### ISSUE TITLE
[Doc]: links to commands-docs failed, returned 404

### ISSUE THREAD

**Issue by owenramber1989** [oceanbase/obdeploy#180]
### Description

The links below cannot be opened. All tries returned error code 404.

### Documentation links

https://github.com/oceanbase/obdeploy/blob/master/docs/en-US/3.user-guide/3.obd-command/2.command-group-for-mirroring-and-warehousing.md
https://github.com/oceanbase/obdeploy/blob/master/docs/en-US/3.user-guide/3.obd-command/1.cluster-command-groups.md
https://github.com/oceanbase/obdeploy/blob/master/docs/en-US/3.user-guide/3.obd-command/3.test-command-group.md

**Comment by frf12** [comment]
Hi,

Thank you for bringing this issue to our attention. We apologize for the inconvenience caused by the broken links.

We have fixed the problem, and the new working links are as follows:

[Command Group for Mirroring and Warehousing](https://github.com/oceanbase/obdeploy/blob/master/docs/en-US/300.obd-command/200.command-group-for-mirroring-and-warehousing.md)
[Cluster Command Groups](https://github.com/oceanbase/obdeploy/blob/master/docs/en-US/300.obd-command/100.cluster-command-groups.md)
[Test Command Group](https://github.com/oceanbase/obdeploy/blob/master/docs/en-US/300.obd-command/300.test-command-group.md)
Please feel free to access the updated documentation using the provided links. If you encounter any further issues or need additional assistance, please don't hesitate to reach out to us.

Thank you for your understanding
